services:
  # Servicio para el backend (plan gratuito)
  - type: web
    name: legal-facil-api
    env: node
    plan: free
    buildCommand: cd legal-facil/server && npm install
    startCommand: cd legal-facil/server && node index.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000

  # Servicio para el frontend (plan gratuito)
  - type: web
    name: legal-facil-frontend
    env: static
    plan: free
    buildCommand: cd legal-facil/client && npm install && npm run build
    staticPublishPath: legal-facil/client/dist
    envVars:
      - key: VITE_API_URL
        value: https://legal-facil-api.onrender.com